project: Chinendar.xcodeproj
retain_objc_accessible: true
schemes:
- Chinendar Mac
- Chinendar Vision
- Chinendar Watch
- Chinendar iOS
- Mac Widget Extension
- Watch Widget Extension
- iOS Widget Extension
targets:
- Chinendar Mac
- Chinendar Vision
- Chinendar Watch
- Chinendar iOS
- Mac Widget Extension
- Watch Widget Extension
- iOS Widget Extension
